version: '3.8'
services:
  app1:
    build:
      context: .
    environment:
      - NODE_ENV="test_app1"
    #ports:
    #  - '3001:3000'
  app2:
    build:
      context: .
    environment:
      - NODE_ENV="test_app2"
    #ports:
    #  - '3002:3000'
  app3:
    build:
      context: .
    environment:
      - NODE_ENV="test_app3"
    #ports:
    #  - '3003:3000'
  load-balancer:
    build:
      context: load-balancer/.
    ports:
      - '9000:80'
